#!/bin/bash

kubectl run postgresql-cli-$(date +%s) --rm --tty -i --restart='Never' --namespace db --image docker.io/bitnami/postgresql:15.1.0-debian-11-r0 --env=PGPASSWORD=$$(kubectl get secret --namespace db postgresql -o jsonpath="{.data.postgres-password}" | base64 -d) --command -- pg_isready --host postgresql -U postgres -d postgres -p 5432
