# https://artifacthub.io/packages/helm/jaegertracing/jaeger
apiVersion: v2
name: jaeger-all-in-one
version: 0.65.4
dependencies:
  - name: jaeger
    version: 0.65.4
    repository: https://jaegertracing.github.io/helm-charts
