apiVersion: v1
kind: ConfigMap
metadata:
  name: opencode-config
  namespace: ai-paperclip
data:
  opencode.json: |
    {
      "$schema": "https://opencode.ai/config.json",
      "permission": {
        "external_directory": "allow"
      },
      "provider": {
        "ollama": {
          "npm": "@ai-sdk/openai-compatible",
          "name": "Ollama",
          "options": {
            "baseURL": "http://ollama.ai-ollama.svc.cluster.local:11434/v1"
          },
          "models": {
            "qwen3.5:9b":{
              "name": "Ollama qwen3.5:9b (32k ctx)",
              "limit": {
                "context": 32768,
                "output": 4096
              }
            }
          }
        },
        "ofox": {
          "npm": "@ai-sdk/openai-compatible",
          "name": "ofox.ai",
          "options": {
            "baseURL": "https://api.ofox.ai/v1",
            "apiKey": "YOUR_API_KEY"
          },
          "models": {
            "z-ai/glm-4.7-flash:free": {
              "name": "GLM-4.7 Flash (Free)",
              "limit": {
                "context": 32768,
                "output": 4096
              }
            }
          }
        }
      }
    }
