apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ai-private-gpt

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - web-ui-deployment.yaml
  - service.yaml
  - web-ui-service.yaml
  - ingress.yaml
