apiVersion: v1
kind: PersistentVolume
metadata:
  name: ai-private-gpt-models
  namespace: ai-private-gpt
  labels:
    name: ai-private-gpt-models
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/datascience-models"
