apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-private-gpt-models
  namespace: ai-private-gpt
spec:
  selector:
    matchLabels:
      name: ai-private-gpt-models
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
