# https://medium.com/sparque-labs/serving-ai-models-on-the-edge-using-nvidia-gpu-with-k3s-on-aws-part-4-dd48f8699116
# nvidia-smi.yaml
apiVersion: batch/v1
kind: Job
metadata:
 name: nvidia-smi
spec:
 template:
  spec:
   runtimeClassName: nvidia
   restartPolicy: Never
   containers:
     - name: cuda-container
       image: nvidia/cuda:11.6.2-base-ubuntu20.04
       #image: nvidia/cuda:12.6.2-base-ubuntu22.04  # too new, driver version not high enough, requires CUDA >= 12.6
       #image: nvidia/cuda:12.6.2-base-ubuntu24.04  # too new, driver version not high enough
       command: ["nvidia-smi"]
       resources:
         limits:
           nvidia.com/gpu: 1 # requesting 1 GPU
