traefik:
  extraObjects:
    - apiVersion: traefik.io/v1alpha1
      kind: Middleware
      metadata:
        name: redirect-https
        namespace: kube-system
      spec:
        redirectScheme:
          scheme: https
          permanent: true
