apiVersion: v1
kind: Service
metadata:
  name: ai-omniparse
  namespace: ai-omniparse
spec:
  selector:
    app: ai-omniparse
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
