apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: private-gpt-models
  namespace: private-gpt
spec:
  selector:
    matchLabels:
      name: private-gpt-models
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
