apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: private-gpt

commonLabels:
  appID: private-gpt

resources:
  - namespace.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
