apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datascience-models
  namespace: private-gpt
spec:
  selector:
    matchLabels:
      name: datascience-models
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
