apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-gpt-web
  namespace: private-gpt
spec:
  replicas: 1  # note: must be 1 pod
  selector:
    matchLabels:
      appID: private-gpt-web
  template:
    metadata:
      annotations:
      labels:
        appID: private-gpt-web
    spec:
      containers:
        - name: main
          image: minixxie/privategpt:a79e02c36dedb0b981e6cfbcd16b4010cb3a909d
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080  # HTTP port
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          volumeMounts:
            - name: private-gpt-models
              # mountPath: /home/worker/app/models/ggml-gpt4all-j-v1.3-groovy.bin
              # subPath: ggml-gpt4all-j-v1.3-groovy.bin
              # mountPath: /home/worker/app/models/mistral-7b-instruct-v0.1.Q8_0.gguf
              # subPath: mistral-7b-instruct-v0.1.Q8_0.gguf
              mountPath: /home/worker/app/models/mistral-7b-instruct-v0.2.Q4_K_M.gguf
              subPath: mistral-7b-instruct-v0.2.Q4_K_M.gguf
            - name: private-gpt-settings-yaml
              mountPath: /home/worker/app/settings.yaml
              subPath: settings.yaml
              readOnly: true
          env:
            - name: MONGO_URI
              value: mongodb://root:hello123@mongodb.db.svc.cluster.local:27017/
          #  - name: PGPT_HF_MODEL_FILE
          #    value: mistral-7b-instruct-v0.1.Q8_0.gguf
      volumes:
        - name: private-gpt-models
          persistentVolumeClaim:
            claimName: private-gpt-models
        - name: private-gpt-settings-yaml
          configMap:
            name: private-gpt-settings-yaml
            items:
              - key: "settings.yaml"
                path: "settings.yaml"
