apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-private-gpt
  namespace: ai-private-gpt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: main
          env:
            - name: MONGO_URI
              value: ''
