apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../kustomize
metadata:
  name: private-gpt

patches:
  - path: configmap.yaml
    target:
      version: v1
      kind: ConfigMap
      name: private-gpt-settings-yaml
  - path: deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: private-gpt
  - path: web-ui-deployment.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: private-gpt-web
