apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: apollo-server-go

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - ingress.yaml
