apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  ollama.override: |
    rewrite name exact ollama-api.local traefik.kube-system.svc.cluster.local
  s3.minio.server: |
    s3.minio.local:53 {
        log
        errors
        template IN A s3.minio.local {
            match ^(.+\.)?s3\.minio\.local\.$
            answer "{{ .Name }} 60 IN CNAME traefik.kube-system.svc.cluster.local."
            upstream
        }
        template IN AAAA s3.minio.local {
            match ^(.+\.)?s3\.minio\.local\.$
            answer "{{ .Name }} 60 IN CNAME traefik.kube-system.svc.cluster.local."
            upstream
        }
        forward . /etc/resolv.conf
    }
