kube-prometheus-stack:
  prometheus:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - prometheus.local
  alertmanager:
    enabled: true
    ingress:
      enabled: true
      hosts:
        - alertmanager.local
  grafana:
    enabled: true
    adminPassword: hello123
    ingress:
      enabled: true
      hosts:
        - grafana.local
  kubernetesServiceMonitors:
    enabled: true
  kubeApiServer:
    enabled: true
  kubelet:
    enabled: true
  kubeControllerManager:
    enabled: true
  kubeEtcd:
    enabled: true
  kubeScheduler:
    enabled: true
  kubeProxy:
    enabled: true
  kubeStateMetrics:
    enabled: true
  nodeExporter:
    enabled: true
  prometheusOperator:
    enabled: true
