apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: docker-pvc
  namespace: ai-openhands
spec:
  #selector:
  #  matchLabels:
  #    name: docker-pvc
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
