apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  labels:
    name: workspace-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /tmp/workspace
