apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: cert-manager-chart
name: cert-manager
repo: https://charts.jetstack.io
version: v1.20.0
releaseName: cert-manager
namespace: cert-manager
valuesFile: values.yaml
includeCRDs: true
