#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

if [ -f Chart.yaml ]; then \
	helm uninstall $(make -s chart-name) -n $(make -s ns) || true; \
fi
if [ -d kustomization ]; then \
	kubectl delete -k kustomization/base/ || true; \
fi
