#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$scriptPath"/var.rc
cd "$scriptPath"

if [ -f Chart.yaml ]; then \
	helm uninstall $(./chart-name) -n $(./ns) || true; \
elif [ -d kustomize ]; then \
	cd kustomize/ ; kubectl delete -k . ; \
fi
