#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

dockerNeedSudo="sudo"
dockerNeedSudo=""

systemctl cat k3s | grep -i docker >/dev/null 2>&1
if [ $? -eq 0 ]; then
	cmd="$dockerNeedSudo docker"
else
	cmd="nerdctl --namespace=k8s.io"
fi

source "$PWD"/var.rc
cd "$PWD"

all=0
ing=0
pvc=0
pv=0
img=0
pod=0
svc=0
deploy=0
if [ "$1" == "" ]; then
	all=1
	ing=1
	pvc=1
	pv=1
	img=1
elif [ "$1" == pod ]; then
	pod=1
elif [ "$1" == svc ]; then
	svc=1
elif [ "$1" == deploy ]; then
	deploy=1
elif [ "$1" == ing ]; then
	ing=1
elif [ "$1" == pvc ]; then
	pvc=1
elif [ "$1" == pv ]; then
	pv=1
elif [ "$1" == img ]; then
	img=1
fi

if [ $all -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get all'
	kubectl -n $(make -s ns) get all
	echo ""
fi
if [ $pod -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get pod'
	kubectl -n $(make -s ns) get pod
	echo ""
fi
if [ $svc -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get svc'
	kubectl -n $(make -s ns) get svc
	echo ""
fi
if [ $deploy -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get deploy'
	kubectl -n $(make -s ns) get deploy
	echo ""
fi
if [ $ing -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get ing'
	kubectl -n $(make -s ns) get ing
	echo ""
fi
if [ $pvc -eq 1 ]; then
	echo '# kubectl -n $(make -s ns) get pvc'
	kubectl -n $(make -s ns) get pvc
	echo ""
fi
if [ $pv -eq 1 ]; then
	echo '# kubectl get pv'
	kubectl get pv
	echo ""
fi
if [ $img -eq 1 ]; then
	for img in $CONTAINER_IMAGES; do
		echo "[$img]"
		imgName=$(echo -n "$img" | cut -f 1 -d ':')
		imgTag=$(echo -n "$img" | cut -f 2 -d ':')
		echo "# $cmd images | grep $imgName | grep $imgTag"
		$cmd images | grep $imgName | grep $imgTag
	done	
	echo ""
fi
