#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$scriptPath"/var.rc
cd "$scriptPath"

all=0
ing=0
pvc=0
pv=0
img=0
pod=0
svc=0
deploy=0
if [ "$1" == "" ]; then
	all=1
	ing=1
	pvc=1
	pv=1
	img=1
elif [ "$1" == pod ]; then
	pod=1
elif [ "$1" == svc ]; then
	svc=1
elif [ "$1" == deploy ]; then
	deploy=1
elif [ "$1" == ing ]; then
	ing=1
elif [ "$1" == pvc ]; then
	pvc=1
elif [ "$1" == pv ]; then
	pv=1
elif [ "$1" == img ]; then
	img=1
fi

if [ $all -eq 1 ]; then
	echo '# kubectl -n $(./ns) get all'
	kubectl -n $(./ns) get all
fi
if [ $pod -eq 1 ]; then
	echo '# kubectl -n $(./ns) get pod'
	kubectl -n $(./ns) get pod
fi
if [ $svc -eq 1 ]; then
	echo '# kubectl -n $(./ns) get svc'
	kubectl -n $(./ns) get svc
fi
if [ $deploy -eq 1 ]; then
	echo '# kubectl -n $(./ns) get deploy'
	kubectl -n $(./ns) get deploy
fi
if [ $ing -eq 1 ]; then
	echo '# kubectl -n $(./ns) get ing'
	kubectl -n $(./ns) get ing
fi
if [ $pvc -eq 1 ]; then
	echo '# kubectl -n $(./ns) get pvc'
	kubectl -n $(./ns) get pvc
fi
if [ $pv -eq 1 ]; then
	echo '# kubectl get pv'
	kubectl get pv
fi
if [ $img -eq 1 ]; then
	echo ""
	for img in $CONTAINER_IMAGES; do
		echo "[$img]"
		imgName=$(echo -n "$img" | cut -f 1 -d ':')
		imgTag=$(echo -n "$img" | cut -f 2 -d ':')
		echo "# nerdctl --namespace=k8s.io images | grep $imgName | grep $imgTag"
		nerdctl --namespace=k8s.io images | grep $imgName | grep $imgTag
	done	
fi
