#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

make helm-repo-add > /dev/null 2>&1 || true
helm show values "$HELM_REPO_ALIAS"/$(make -s --no-print-directory chart-name)
