#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$scriptPath"/var.rc
cd "$scriptPath"

for img in $CONTAINER_IMAGES; do
	echo "[$img]"
	imgName=$(echo -n "$img" | cut -f 1 -d ':')
	imgTag=$(echo -n "$img" | cut -f 2 -d ':')
	echo "$imgName"
	echo "$imgTag"
	fileImgName=$(echo -n "$imgName" | sed 's/\//__/g')
	f="$fileImgName"___"$imgTag.tar"
	if [ -f "$f" ]; then
		nerdctl --namespace=k8s.io images | grep "$imgName" | grep "$imgTag"
		if [ $? -ne 0 ]; then
			echo "Import from file..."
			nerdctl load -i "$f" --namespace=k8s.io
			nerdctl --namespace=k8s.io images | grep "$imgName" | grep "$imgTag"
		fi
	else
		echo >&2 "WARN: file not exists: $f"
		nerdctl --namespace=k8s.io images | grep "$imgName" | grep "$imgTag"
		if [ $? -ne 0 ]; then
			echo "Pulling image..."
			nerdctl pull "$img" --namespace=k8s.io
		fi
		nerdctl save "$img" --output "$f" --namespace=k8s.io
		ls -lt "$f"
	fi
done
