#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

dockerNeedSudo="sudo"
dockerNeedSudo=""

systemctl cat k3s | grep -i docker >/dev/null 2>&1
if [ $? -eq 0 ]; then
	cmd="$dockerNeedSudo docker"
else
	cmd="nerdctl --namespace=k8s.io"
fi

for img in $CONTAINER_IMAGES; do
	echo "[$img]"
	imgName=$(echo -n "$img" | cut -f 1 -d ':')
	imgTag=$(echo -n "$img" | cut -f 2 -d ':')
	echo "$imgName"
	echo "$imgTag"
	fileImgName=$(echo -n "$imgName" | sed 's/\//__/g')
	f="$fileImgName"___"$imgTag.tar"
	if [ -f "$f" ]; then
		$cmd images | grep "$imgName " | grep "$imgTag"
		if [ $? -ne 0 ]; then
			echo "Import from file..."
			$cmd load -i "$f"
			$cmd images | grep "$imgName " | grep "$imgTag"
		fi
	else
		echo >&2 "WARN: file not exists: $f"
		$cmd images | grep "$imgName " | grep "$imgTag"
		if [ $? -ne 0 ]; then
			echo "Pulling image..."
			$cmd pull "$img"
		fi
		$cmd save "$img" --output "$f" || true
		ls -lt "$f"
	fi
done
