#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

if [ -f Chart.yaml ]; then
	helm dep update .
	helm upgrade --install --wait $(make -s chart-name) . -n $(make -s ns) --create-namespace -f values.local.yaml
elif [ -d kustomization ]; then
	kubectl apply -k kustomization/overlays/local
fi
