#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$scriptPath"/var.rc
cd "$scriptPath"

if [ -f Chart.yaml ]; then
	helm dep update .
	helm upgrade --install --wait $(./chart-name) . -n $(./ns) --create-namespace -f values.local.yaml
elif [ -d kustomization ]; then
	kubectl apply -k kustomization/overlays/local
fi
