#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

kubectl -n $(make -s --no-print-directory ns) rollout restart deployment $(kubectl -n $(make -s --no-print-directory ns) get deployment | sed 1d | awk '{print $1}')
