#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

source "$PWD"/var.rc
cd "$PWD"

if [ -d kustomization ]; then
	kubectl apply -k kustomization/base
elif [ -f Chart.yaml ]; then
	helm dep update .
	helm upgrade --install --wait $(make -s --no-print-directory chart-name) . -n $(make -s --no-print-directory ns) --create-namespace
fi
