#!/bin/bash

cat <<EOF | curl -v -H 'Content-Type: application/json; charset=utf-8' -X POST --data-binary @- http://ollama-api.local/api/generate
{"model":"llama3.1","prompt":"Hello"}
EOF
#curl -v http://ollama-api.local/api/generate -d '{"model":"llama3.1","prompt":"Hello"}'
#curl -v http://ollama-api.local/api/generate -d '{"model":"llama3.1","prompt":"why is the sky blue?"}'
