#!/bin/bash

curl -v http://ollama-api.local/api/generate -d '{"model":"llama3.1","prompt":"Hello"}'
#curl -v http://ollama-api.local/api/generate -d '{"model":"llama3.1","prompt":"why is the sky blue?"}'
