ollama:
  image:
    tag: "0.3.9"
  ollama:
    gpu:
      # enable gpu if your k8s containerd/docker has gpu support
      enabled: true
    models:
      - llama3.1
      #- mistral
  ingress:
    enabled: true
    hosts:
    - host: ollama-api.local  # use a production hostname
      paths:
        - path: /
          pathType: Prefix

