apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ai-ragflow

resources:
  - initdb-job.yaml
  - namespace.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
