apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datascience-models
  namespace: ai-ktransformers
spec:
  selector:
    matchLabels:
      name: ai-ktransformers-datascience-models
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
