#!/bin/bash

scriptPath=$(cd $(dirname "$0") && pwd)

cd "$scriptPath"

echo -n "MySQL root pass: "
kubectl get secret --namespace infra-mysql mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d
echo ""

ts=$(date "+%s")
kubectl run mysql-client-$ts --rm --tty -i --restart='Never' --image docker.io/mysql:8.2.0 --namespace infra-mysql --env MYSQL_ROOT_PASSWORD=$(kubectl get secret --namespace infra-mysql mysql -o jsonpath="{.data.mysql-root-password}" | base64 -d) --command -- bash -c 'mysql -h mysql.infra-mysql.svc.cluster.local -uroot -p"$MYSQL_ROOT_PASSWORD" -e "DROP DATABASE \`infra_apollo_config\`; DROP USER \`infra_apollo_config\`; DROP DATABASE \`infra_apollo_portal\`; DROP USER \`infra_apollo_portal\`;"'
